### ISSUE TITLE
How to deploy ford to multiple computing nodes

### ISSUE THREAD

**Issue by yzx2337** [minghust/ford#1]
The example briefly illustrates the situation of one computing node. I want to know how to modify the configuration if FORD is used on multiple computing nodes. At the same time I want to know if the code needs to be modified?

**Comment by minghust** [comment]
Thanks for reaching out! 
Currently this code supports 1 compute node to complete the basic functionality. If needing more compute nodes, you may need to modify the configuations and codes to support that. Thank you.
